### PR TITLE
Feat: upload 3 images

### LINKED ISSUE #1: 我要超市A60🥵
60 快给我更多的60🥵🥵🥵

### PR DESCRIPTION
**Pull request by MingxuanGame**

### CODE REVIEW

**Comment by NoNormalCreeper** [comment]
`index.md` is also needed to edit(

**Comment by MingxuanGame** [comment]
> `index.md` is also needed to edit(

https://github.com/modcrafts/a60-shop/blob/577ef711a92281c94d717384f2e23419e8b45b44/index.md?plain=1#L27

**Comment by NoNormalCreeper** [comment]
sorry, im shabby, i didnt see it.

**Comment by modcrafts** [comment]
Approved, thank you

**Review by modcrafts — APPROVED** [review]

**Pull request merged**
